@url = http://localhost:3000/api/v1/
@user = {{url}}user/

@randomNumber = {{$randomInt 0 9999999}}



### @name createUser
POST {{user}} HTTP/1.1
Content-Type: application/json

{
    "firstName": "Test",
    "lastName": "USER",
    "username": "useruser{{randomNumber}}",
    "email": "mail{{randomNumber}}@mail.com",
    "password": "123456789",
    "role": "USER"
}

### @name login
POST {{url}}login HTTP/1.1
Content-Type: application/json
    # "username": "useruser",

{
    "email": "mail@mail.com",
    "password": "123456789"
}

