@url = http://localhost:3000/api/v1/
@user = {{url}}user/

@randomNumber = {{$randomInt 0 9999999}}
@token = {{login.response.body.$.token}}

### CREATE USER
# @name createUser
POST {{user}} HTTP/1.1
Content-Type: application/json

{
    "firstName": "Test",
    "lastName": "USER",
    "username": "useruser{{randomNumber}}",
    "email": "mail{{randomNumber}}@mail.com",
    "password": "1aB!cD0*",
    "role": "USER"
}

### LOG IN
# @name login
POST {{url}}login HTTP/1.1
Content-Type: application/json

# "username": "useruser",
{
    "email": "mail@mail.com",
    "password": "1aB!cD0*"
}

### GET USER WITH USERNAME
# @name getUser
GET {{user}}useruser HTTP/1.1
Content-Type: application/json

### UPDATE USER PUT 
# @name updateUser
PUT {{user}} HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
    "password": "1aB!cD0*",
    "user": {
        "firstName": "TestUser",
        "lastName": "USERUSER",
        "username": "useruser{{randomNumber}}",
        "email": "mail{{randomNumber}}@mail.com",
        "password": "1aB!cD0*",
        "role": "SELLER"
    }
}

### UPDATE USER PATCH 
# @name updateUser
PATCH  {{user}} HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
    "password": "1aB!cD0*",
    "user": {
        "role": "USER"
    }
}

### FREEZE ACCOUNT
# @name freezeAccount
PATCH {{user}}freeze HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
    "password": "1aB!cD0*"
}

### DELETE USER
# @name delete
DELETE {{user}} HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
    "password": "1aB!cD0*"
}